In [20]:
import cv2

## Loading Mask RCNN

In [21]:
net = cv2.dnn.readNetFromTensorflow('downloads/source code/dnn/frozen_inference_graph_coco.pb',
                                   'downloads/source code/dnn/mask_rcnn_inception_v2_coco_2018_01_28.pbtxt')

In [22]:
img = cv2.imread('downloads/source code/road.jpg')

### Load Image

In [4]:
img = cv2.imread('downloads/source code/road.jpg')
cv2.imshow('Image', img)
cv2.waitKey(0)

27

In [23]:
height, width, _ = img.shape

### Detect object (draw the box)



In [24]:
# We need to convert the image to model-readable format.

blob = cv2.dnn.blobFromImage(img, swapRB=True)
net.setInput(blob)
boxes, masks = net.forward(['detection_out_final','detection_masks'])

In [25]:
print(boxes)

[[[[ 0.          0.          0.9982508   0.6005737   0.30911264
     0.71964794  0.92962635]
   [ 0.          0.          0.99765694  0.9214836   0.2776569
     0.9835165   0.54178905]
   [ 0.          0.          0.99711895  0.4406094   0.2849804
     0.49243158  0.49068603]
   [ 0.          0.          0.9958181   0.5128468   0.2724591
     0.5533583   0.49174023]
   [ 0.         17.          0.99581605  0.3635242   0.8000454
     0.5755868   0.9281951 ]
   [ 0.          7.          0.97837114  0.7109451   0.21397197
     0.80681336  0.37949353]
   [ 0.          7.          0.97000545  0.7860096   0.20279637
     0.9751641   0.4042512 ]
   [ 0.          0.          0.95207167  0.25897604  0.28407577
     0.28255582  0.38739482]
   [ 0.          2.          0.94219637  0.          0.27940008
     0.11640605  0.40211287]
   [ 0.          0.          0.90971375  0.38854766  0.2789147
     0.41123998  0.3713565 ]
   [ 0.          2.          0.88748515  0.08032143  0.26250428
     0.1796

In [26]:
print(masks)

[[[[6.18432096e-05 3.31879783e-05 1.37609532e-05 ... 5.55937886e-02
    6.45361608e-03 1.74350804e-03]
   [8.69457563e-06 5.44354998e-06 3.28249462e-06 ... 8.97845089e-01
    2.53759593e-01 1.13165919e-02]
   [1.21471221e-05 4.40540043e-06 3.64316361e-06 ... 8.99573147e-01
    3.60054255e-01 2.22266242e-02]
   ...
   [7.77568221e-06 1.36644558e-05 2.64138100e-04 ... 9.65586066e-01
    8.44371259e-01 1.00281879e-01]
   [1.00063990e-05 3.75881318e-05 5.90223062e-04 ... 8.90574872e-01
    9.24418211e-01 4.33798641e-01]
   [3.76500502e-05 5.40783913e-05 4.07981308e-04 ... 1.22418571e-02
    1.24758100e-02 1.00488812e-02]]

  [[3.79232573e-03 2.25386769e-03 3.22574982e-03 ... 6.65766001e-02
    4.88290042e-02 2.66914368e-02]
   [7.08522974e-04 2.81443674e-04 2.24411677e-04 ... 1.36416465e-01
    1.06386080e-01 4.65156473e-02]
   [1.01109094e-03 4.07430751e-04 3.37937206e-04 ... 1.50041401e-01
    1.55688301e-01 6.26220778e-02]
   ...
   [2.65493174e-04 7.51641463e-04 5.18767955e-03 ... 2.68

In [27]:
boxes.shape

(1, 1, 100, 7)

In [28]:
# Number of objects detected
detection_count = boxes.shape[2]
print(detection_count)

100


In [29]:
box = boxes[0,0,0]
box

array([0.        , 0.        , 0.9982508 , 0.6005737 , 0.30911264,
       0.71964794, 0.92962635], dtype=float32)

In [11]:
x = int(box[3] * width)
y = int(box[4] * height)
x2 = int(box[5] * width)
y2 = int(box[6] * height)

In [12]:
print(x,y)

768 264


In [13]:
cv2.rectangle(img,(x,y),(x2,y2),(255,0,0), 3)

array([[[ 74,  98, 118],
        [110, 131, 152],
        [118, 136, 159],
        ...,
        [172, 167, 166],
        [161, 156, 155],
        [147, 142, 141]],

       [[ 68,  92, 112],
        [106, 127, 148],
        [119, 138, 159],
        ...,
        [201, 196, 195],
        [197, 192, 191],
        [192, 187, 186]],

       [[ 65,  89, 107],
        [ 93, 115, 133],
        [104, 121, 140],
        ...,
        [207, 202, 201],
        [207, 202, 201],
        [208, 203, 202]],

       ...,

       [[126, 124, 124],
        [114, 112, 112],
        [109, 108, 110],
        ...,
        [137, 132, 134],
        [127, 124, 126],
        [114, 113, 115]],

       [[108, 106, 106],
        [101,  99,  99],
        [ 99,  96,  98],
        ...,
        [134, 131, 133],
        [133, 132, 134],
        [123, 122, 124]],

       [[123, 118, 119],
        [101,  99,  99],
        [ 92,  89,  91],
        ...,
        [126, 123, 125],
        [138, 137, 139],
        [152, 151, 153]]

In [18]:
cv2.imshow('Image', img)
cv2.waitKey(0)

113

## Object Detection in Image

In [10]:
for i in range(detection_count):
    box = boxes[0,0,i]
    x = int(box[3] * width)
    y = int(box[4] * height)
    x2 = int(box[5] * width)
    y2 = int(box[6] * height)
    cv2.rectangle(img,(x,y),(x2,y2),(255,0,0), 3)

cv2.imshow('Image', img)
cv2.waitKey(0)

113

In [30]:
# create a black image
import numpy as np
black_image = np.zeros((height, width,3), np.uint8)

In [31]:
black_image.shape

(855, 1280, 3)

In [34]:
for i in range(detection_count):
    box = boxes[0, 0, i]
    class_id = box[1]
    score = box[2]
    if score < 0.5:
        continue

    # Get box Coordinates
    x = int(box[3] * width)
    y = int(box[4] * height)
    x2 = int(box[5] * width)
    y2 = int(box[6] * height)

    roi = black_image[y: y2, x: x2]
    roi_height, roi_width, _ = roi.shape

    # Get the mask
    mask = masks[i, int(class_id)]
    mask = cv2.resize(mask, (roi_width, roi_height))
    _, mask = cv2.threshold(mask, 0.5, 255, cv2.THRESH_BINARY)

    cv2.rectangle(img, (x, y), (x2, y2), (255, 0, 0), 3)
    colors = np.random.randint(0,255,(80,3))

    # Get mask coordinates
    contours, _ = cv2.findContours(np.array(mask, np.uint8), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    color = colors[int(class_id)]
    for cnt in contours:
        cv2.fillPoly(roi, [cnt], (int(color[0]), int(color[1]), int(color[2])))

    # cv2.imshow("roi", roi)
    # cv2.waitKey(0)


cv2.imshow("Image", img)
cv2.imshow("Black image", black_image)
cv2.waitKey(0)

In [17]:
colors = np.random.randint(0,255,(80,3))
print(colors)

[[123  58 132]
 [145 226 242]
 [ 12 171 185]
 [ 17 124 213]
 [ 53 117  36]
 [ 31 123 254]
 [ 96  91 208]
 [ 97 117  92]
 [246  74   0]
 [228   8  77]
 [159   2 119]
 [133 181 111]
 [224 152  92]
 [ 29  59  74]
 [ 66 209  96]
 [ 89 220  96]
 [240 122 200]
 [ 72 232 103]
 [ 45   6 196]
 [176  36 105]
 [237 116 114]
 [133   1 252]
 [111 254 175]
 [148  50 100]
 [197  85 249]
 [237  96 209]
 [ 79  40 235]
 [214  77  68]
 [ 39 173 235]
 [118  24 125]
 [ 60  16  90]
 [155 178 121]
 [ 77 110 154]
 [111 232  33]
 [ 62 247 179]
 [211  15  27]
 [ 56 109   2]
 [250 190 150]
 [ 42 251  18]
 [121  21  89]
 [ 93 172  77]
 [ 98 197  83]
 [ 97  63  18]
 [ 20  23 241]
 [ 71 132 145]
 [218  90 241]
 [248 131 223]
 [210  76  59]
 [203 120 203]
 [ 93 124  20]
 [248 167 180]
 [ 84 201   4]
 [247  84  76]
 [235 104  63]
 [ 11 218 123]
 [ 90  90 234]
 [112  29  99]
 [144  98  86]
 [ 36  38 239]
 [111 170  61]
 [152 124  37]
 [ 19  34  66]
 [ 67  62 158]
 [225  57  49]
 [238  10 129]
 [ 59 220 170]
 [139 196 